dist: trusty
sudo: required

addons:
  apt:
    packages:
      - lcov
      - libboost-all-dev
      - libmysqlclient-dev

language: cpp

env:
  global:
    - ASIO_TARBALL=https://github.com/chriskohlhoff/asio/archive/asio-1-10-6.tar.gz
    - CPLUS_INCLUDE_PATH=asio/include

cache:
  directories:
    - asio

before_script:
  - mysql -u root < test/init.sql
  - curl --silent --location $ASIO_TARBALL | tar --strip-components=1 -xzf -

matrix:
  include:
    - compiler: clang
      env:
        - USE_BOOST_ASIO=0
    - compiler: clang
      env:
        - USE_BOOST_ASIO=1

services: mysql

script: scons USE_BOOST_ASIO=${USE_BOOST_ASIO:-0}
