dist: trusty
sudo: required

addons:
  apt:
    packages:
      - lcov
      - libboost-all-dev
      - libmysqlclient-dev

language: cpp

matrix:
  include:
    - compiler: clang
      env:
        - CPLUS_INCLUDE_PATH=asio-1-10-6/asio/include
        - USE_BOOST_AIO=0
    - compiler: clang
      env:
        - CPLUS_INCLUDE_PATH=asio-1-10-6/asio/include
        - USE_BOOST_AIO=1

services: mysql

before_script:
  - mysql -u root < test/init.sql
  - git clone --branch asio-1-10-6 https://github.com/chriskohlhoff/asio.git asio-1-10-6

script: scons USE_BOOST_ASIO=${USE_BOOST_ASIO:-0}
